### PR TITLE
Extend Tachyons with egghead colors

### PR DESCRIPTION
**Pull request by ltclmbdev**
colors

### CODE REVIEW

**Comment by ltclmbdev** [comment]
Taylor, Trevor: what is the good place to put our custom css helpers? Inside this repo? Or we want to keep separate .css file somewhere outside?

**Comment by joelhooks** [comment]
@DrShpongle this effectively means we will never be pulling in from upstream tachyons, so where you place the modules doesn't really matter, if I understand correctly. It would probably make more sense to just copy all of this into tachyons-egghead since we already publish it.

**Comment by tayiorbeii** [comment]
@DrShpongle Agree with @joelhooks ... I don't think it matters, and would probably make sense to do this in `tachyons-egghead`.

**Comment by ltclmbdev** [comment]
tachyons-egghead imports every separate tachyons module what means that we need to fork every of these modules and update them with breakpoints variables (each separate module duplicate these vars inside unlike single-repo where I need to change only one file). Is it argue to use single-repo?

**Comment by tayiorbeii** [comment]
@DrShpongle Talking with my friend, he seems to recall that the very last (or possibly very first) `@media` that is declared in an individual module _should_ override everything else. This should be easy to test in our already-broken-up version.

**Comment by tayiorbeii** [comment]
@DrShpongle So we can declare everything at the bottom of https://github.com/eggheadio/tachyons-egghead/blob/master/src/tachyons.css#L85 and be able to just do the variables once, and then when PostCSS builds Tachyons, it will override everything.

```
@import 'tachyons-widths';
@import 'tachyons-spacing';

@custom-media --breakpoint-not-small screen and (min-width: 69em);
@custom-media --breakpoint-medium screen and (min-width: 69em) and (max-width: 420em);
@custom-media --breakpoint-large screen and (min-width: 420em);
```

**Comment by ltclmbdev** [comment]
That's cool, @tayiorbeii let's use this approach

**Comment by ltclmbdev** [comment]
That's work! Closing PR.

**Pull request closed without merging**
